spring:
  application:
    name: reactive
  sql:
    init:
      mode: always
  docker:
    compose:
      lifecycle-management: start_and_stop

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
jwt:
  token:
    secret: JDJhJDEyJGNWTS44Z0hFQk1oeEluVFhyV2N0UGVwWktIZUV5VlY2QURzWWVsYlQ4U25mUm5KMGhFdkZ1
    lifeTime: 30m